// resources/js/views/partials/slim/slim.react.jsx
/*
 * Slim v5.3.1 - Image Cropping Made Easy
 * Copyright (c) 2020 Rik Schennink - https://pqina.nl/slim
 */
// Necessary React Modules
import React from 'react';
import ReactDOM from 'react-dom';

// Slim (place slim CSS and module js file in same folder as this file)
import Slim from './slim.module.js';
import './slim.min.css';

// React Component
export default class extends React.Component {

	componentDidMount() {
		var root = ReactDOM.findDOMNode(this);
		if (this.props.initialImage) {
			var img = document.createElement('img');
			img.setAttribute('alt', '');
			img.src = this.props.initialImage;
			root.appendChild(img);
		}
		this.instance = Slim ? Slim.create(root, this.props) : null;
	}

	render() {
		return <div className="slim">{ this.props.children }</div>
	}

};

// resources/js/views/partials/slim/slim.vue
/*
 * Slim v5.3.1 - Image Cropping Made Easy
 * Copyright (c) 2020 Rik Schennink - https://pqina.nl/slim
 */
<template>
  <div class="slim">
    <slot />
  </div>
</template>

<script>
// Slim (place slim CSS and slim.module.js file in same folder as this file)
import Slim from './slim.module.js'

var instance = null

export default {
  name: 'slim-cropper',
  props: ['options'],
  mounted: function () {
    if (this.options.initialImage) {
      var img = document.createElement('img')
      img.setAttribute('alt', '')
      img.src = this.options.initialImage
      this.$el.appendChild(img)
    }
    instance = new Slim(this.$el, this.options)
  },
  beforeUnmount: function () {
    instance.destroy()
  }
}
</script>
<style lang="css">
    @import "./slim.min.css";
</style>
